apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "bulldozer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bulldozer.name" . }}
    helm.sh/chart: {{ include "bulldozer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bulldozer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bulldozer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        {{ range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote}}
        {{- end }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      volumes:
        - name: config
          configMap:
            name: bulldozer-config
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: "GITHUB_KEY"
              valueFrom:
                secretKeyRef:
                  key:  githubkey
                  name: {{ .Release.Name }}-auth
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /secrets/bulldozer.yml
              subPath: bulldozer.yml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
